export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './companyCo2YearlyController.service';
import { CompanyCo2YearlyControllerService } from './companyCo2YearlyController.service';
export * from './companyController.service';
import { CompanyControllerService } from './companyController.service';
export * from './coordinateController.service';
import { CoordinateControllerService } from './coordinateController.service';
export * from './dashboardController.service';
import { DashboardControllerService } from './dashboardController.service';
export * from './landController.service';
import { LandControllerService } from './landController.service';
export * from './loopsController.service';
import { LoopsControllerService } from './loopsController.service';
export * from './loopsWebhookController.service';
import { LoopsWebhookControllerService } from './loopsWebhookController.service';
export * from './ordersController.service';
import { OrdersControllerService } from './ordersController.service';
export * from './pingController.service';
import { PingControllerService } from './pingController.service';
export * from './plannedPlantationController.service';
import { PlannedPlantationControllerService } from './plannedPlantationController.service';
export * from './purchaseController.service';
import { PurchaseControllerService } from './purchaseController.service';
export * from './redsysPaymentsController.service';
import { RedsysPaymentsControllerService } from './redsysPaymentsController.service';
export * from './treeController.service';
import { TreeControllerService } from './treeController.service';
export * from './treeTypeController.service';
import { TreeTypeControllerService } from './treeTypeController.service';
export * from './uploadsController.service';
import { UploadsControllerService } from './uploadsController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export const APIS = [AuthControllerService, CompanyCo2YearlyControllerService, CompanyControllerService, CoordinateControllerService, DashboardControllerService, LandControllerService, LoopsControllerService, LoopsWebhookControllerService, OrdersControllerService, PingControllerService, PlannedPlantationControllerService, PurchaseControllerService, RedsysPaymentsControllerService, TreeControllerService, TreeTypeControllerService, UploadsControllerService, UserControllerService];
