/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CompanyCO2YearlyRequestDto { 
    id?: number;
    year?: number;
    totalEmissions?: number;
    totalCompensations?: number;
}

