/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSummaryResponseDto } from './userSummaryResponse';
import { CompanyCO2YearlyResponseDto } from './companyCO2YearlyResponse';


export interface CompanyResponseDto { 
    id?: number;
    name?: string;
    address?: string;
    picture?: string;
    users?: Array<UserSummaryResponseDto>;
    createdAt?: string;
    co2?: Array<CompanyCO2YearlyResponseDto>;
}

