/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Email del usuario que olvidó la contraseña
 */
export interface ForgotPasswordRequestDto { 
    email?: string;
}

