/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoordinateRequestDto } from './coordinateRequest';


export interface LandRequestDto { 
    name?: string;
    description?: string;
    location?: string;
    area?: number;
    userIds?: Array<number>;
    companyIds?: Array<number>;
    picture?: string;
    maxTrees?: number;
    coordinates?: Array<CoordinateRequestDto>;
}

