/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LandUpdateRequestDto { 
    name?: string;
    description?: string;
    location?: string;
    area?: number;
    picture?: string;
    maxTrees?: number;
    coordinates?: Array<any>;
}

