/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LandResponseDto { 
    id?: number;
    name?: string;
    description?: string;
    location?: string;
    area?: number;
    picture?: string;
    maxTrees?: number;
    createdAt?: string;
    userIds?: Array<number>;
    companyIds?: Array<number>;
    coordinates?: Array<any>;
}

