/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObjectDto } from './pageableObject';
import { UserResponseDto } from './userResponse';
import { SortObjectDto } from './sortObject';


export interface PageUserResponseDto { 
    totalElements?: number;
    totalPages?: number;
    number?: number;
    sort?: SortObjectDto;
    numberOfElements?: number;
    first?: boolean;
    last?: boolean;
    pageable?: PageableObjectDto;
    size?: number;
    content?: Array<UserResponseDto>;
    empty?: boolean;
}

