/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PlannedPlantationKpiResponseDto { 
    plantationId?: number;
    plantationName?: string;
    minTrees?: number;
    optimalTrees?: number;
    maxTrees?: number;
    soldTrees?: number;
}

