/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PurchaseResponseDto { 
    landName?: string;
    treeTypeId?: number;
    quantity?: number;
    totalPrice?: number;
}

