/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RedsysPaymentResponseDto { 
    /**
     * URL de Redsys donde redirigir al usuario
     */
    redsysUrl?: string;
    /**
     * Parámetros firmados necesarios para el pago
     */
    parameters?: { [key: string]: string; };
}

