/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Email y contraseña del usuario
 */
export interface RegisterUserRequestDto { 
    name?: string;
    surname?: string;
    secondSurname?: string;
    email?: string;
    password?: string;
    receiveEmails?: boolean;
    role?: RegisterUserRequestDto.RoleEnum;
    companyId?: number;
    picture?: string;
}
export namespace RegisterUserRequestDto {
    export const RoleEnum = {
        Admin: 'ADMIN',
        User: 'USER',
        CompanyAdmin: 'COMPANY_ADMIN',
        CompanyUser: 'COMPANY_USER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


