/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterUserByAdminRequestDto { 
    name?: string;
    surname?: string;
    secondSurname?: string;
    email?: string;
    role?: RegisterUserByAdminRequestDto.RoleEnum;
    companyId?: number;
    picture?: string;
    pendingTreesCount?: number;
    accountLocked?: boolean;
    receiveEmails?: boolean;
}
export namespace RegisterUserByAdminRequestDto {
    export const RoleEnum = {
        Admin: 'ADMIN',
        User: 'USER',
        CompanyAdmin: 'COMPANY_ADMIN',
        CompanyUser: 'COMPANY_USER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


