/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Nueva contraseña
 */
export interface ResetPasswordRequestDto { 
    currentPassword?: string;
    newPassword?: string;
}

