/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TreeTypeRequestDto { 
    name?: string;
    scientificName?: string;
    description?: string;
    co2AbsorptionAt20?: number;
    co2AbsorptionAt25?: number;
    co2AbsorptionAt30?: number;
    co2AbsorptionAt35?: number;
    co2AbsorptionAt40?: number;
    typicalHeight?: number;
    lifespanYears?: number;
    picture?: string;
}

