/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TreeTypeResponseDto } from './treeTypeResponse';
import { LandResponseDto } from './landResponse';
import { PlannedPlantationResponseDto } from './plannedPlantationResponse';


export interface TreeResponseDto { 
    id?: number;
    scientificName?: string;
    customName?: string;
    co2AbsorptionAt20?: number;
    co2AbsorptionAt25?: number;
    co2AbsorptionAt30?: number;
    co2AbsorptionAt35?: number;
    co2AbsorptionAt40?: number;
    picture?: string;
    plantedAt?: string;
    plannedPlantation?: PlannedPlantationResponseDto;
    treeTypeId?: number;
    treeTypeName?: string;
    treeType?: TreeTypeResponseDto;
    landId?: number;
    landName?: string;
    land?: LandResponseDto;
    ownerUserId?: number;
    ownerUserName?: string;
    ownerCompanyId?: number;
    ownerCompanyName?: string;
}

