/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TreeRequestDto { 
    scientificName?: string;
    customName?: string;
    co2AbsorptionAt20?: number;
    co2AbsorptionAt25?: number;
    co2AbsorptionAt30?: number;
    co2AbsorptionAt35?: number;
    co2AbsorptionAt40?: number;
    plantedAt?: string;
    treeTypeId?: number;
    landId?: number;
    ownerUserId?: number;
    ownerCompanyId?: number;
    plannedPlantationId?: number;
    picture?: string;
}

