/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TreeBatchPlantRequestDto { 
    landId?: number;
    treeTypeId?: number;
    quantity?: number;
    ownerUserId?: number;
    ownerCompanyId?: number;
    plannedPlantationId?: number;
}

