/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserSummaryResponseDto { 
    id?: number;
    name?: string;
    surname?: string;
    email?: string;
    role?: UserSummaryResponseDto.RoleEnum;
}
export namespace UserSummaryResponseDto {
    export const RoleEnum = {
        Admin: 'ADMIN',
        User: 'USER',
        CompanyAdmin: 'COMPANY_ADMIN',
        CompanyUser: 'COMPANY_USER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


