/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CompanyResponseDto } from './companyResponse';


export interface UserResponseDto { 
    id: number;
    name: string;
    email: string;
    surname?: string;
    secondSurname?: string;
    picture?: string;
    role?: UserResponseDto.RoleEnum;
    emailVerified?: boolean;
    forcePasswordChange?: boolean;
    pendingTreesCount?: number;
    lastLoginAt?: string;
    loginCount?: number;
    accountLocked?: boolean;
    receiveEmails?: boolean;
    company?: CompanyResponseDto;
}
export namespace UserResponseDto {
    export const RoleEnum = {
        Admin: 'ADMIN',
        User: 'USER',
        CompanyAdmin: 'COMPANY_ADMIN',
        CompanyUser: 'COMPANY_USER'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


